ebryn/ember-component-css

index.js
Addresses [#7](https://github.com/ebryn/ember-component-css/issues/7).
Sets the `srcDir` used by the preprocessor to either be the `podModulePrefix` path (adjusted to the `app` folder rather than `<app-name>` folder) or defaults to `app` (current behavior).
=> Add support for podModulePrefix

index.js
Addresses [#11](https://github.com/ebryn/ember-component-css/issues/11).
Allows usage of either `&` or `:--component` to reference the component selector within the current implementation.
=> Add `:--component` pseudo-class as alternative to `&`

index.js
It seems that pickFiles has been deprecated in favour of 'broccoli-funnel', see: https://github.com/ember-cli/ember-cli/blob/master/CHANGELOG.md#022
I am not sure if there is any difference between `this.pickFiles -> require('broccoli-funnel');` and `this.Funnel -> require('broccoli-funnel');`. But doesn't seem to me like there is any.
=> Update deprecated API for ember-cli 0.2.2

index.js
This tweak accommodates components that are nested more than one pod deep, rather than assuming they're at the top level. This came in handy for one of the acceptance tests I was putting together for a forthcoming PR.
Note that the generated class name gets a `--` in place of the `/` in the original path. Given the GUID, there shouldn't ever be an actual conflict, but if you think the visual similarity to BEM's "modifier" notation might annoy some, I'm happy to change it.
=> Handle namespaced components

README.md, index.js, lib/broc-component-css-preprocessor.js, lib/component-css-postprocessor.js, package.json, tests/dummy/app/my-component/styles.css, tests/dummy/app/styles/app.css, tests/dummy/app/styles/app.scss
Add stylus support, update readme, and prevent non-CSS styles from being appended to vendor.css
Verified that #21 (Less) works and added support for #22 (Stylus). Also fixed an oversight where non-processed stuff (like `.scss` code) was getting appended to `vendor.css`.
Oh, and I removed the `ember-cli-sass` dev dependency. I assume any time we want to test a preprocessor we can just install it locally and remove it when finished.
=> Add stylus support, update readme, and prevent non-CSS styles from being appended to vendor.css

lib/broc-component-css-preprocessor.js, tests/dummy/app/acceptance/tests/pod-component-in-components/expectation.js, tests/dummy/app/acceptance/tests/pod-component-in-components/template.hbs, tests/dummy/app/acceptance/tests/pod-component-in-pod/expectation.js, tests/dummy/app/acceptance/tests/pod-component-in-pod/template.hbs, tests/dummy/app/acceptance/tests/pod-component-in-root/expectation.js, tests/dummy/app/acceptance/tests/pod-component-in-root/template.hbs, tests/dummy/app/components/pod-component-in-components/styles.css, tests/dummy/app/components/pod-component-in-components/template.hbs, tests/dummy/app/outer-pod/inner-pod/pod-component-in-pod/styles.css, tests/dummy/app/outer-pod/inner-pod/pod-component-in-pod/template.hbs, tests/dummy/app/pod-component-in-root/styles.css, tests/dummy/app/pod-component-in-root/template.hbs
This should fix #28.
It also adds some general acceptance tests for various valid component locations using the default Ember CLI resolver. In the future we might want to consider an interface to support people using custom resolvers.
=> Handle components in the `/components` directory.

README.md
Noticed the badge just linked to itself instead of the Travis page for the project.
=> Fix Travis link

lib/broc-component-css-preprocessor.js
Address #33. Should also fix an uncaught issue with `.styl` files as well (if you had multiple files, the indentation was incorrect due to a potential missing newline).
=> Add support for .sass extension

lib/component-css-preprocessor.js
Addresses #40.
The issue with `production` builds was being caused by extra JS files being included during the minification step. This was happening because the tree we were returning from our `ComponentCssPreprocessor` included almost the entire project. That is because we needed access to folders other than `app/styles`, which is normally what gets filtered down to in other CSS preprocessors. That was fixable by a simple funnel.
Tested to make sure it worked with `ember-cli-sass` and vanilla CSS.
=> Fix production builds

package.json, tests/.jshintrc, tests/lib/component-css-preprocessor.js
First of the three plugins mentioned in #26.
These tests are fairly simple. The only real functionality in `ComponentCssPreprocessor` is to filter out everything but the styles directory and add the `pod-styles` file which comes from the `BrocComponentCssPreprocessor`. Will be adding additional pull requests with tests for the other plugins soon.
=> ComponentCssPreprocessor tests

index.js
This small change ensures that the components from addons will be found and added to the component lookup table that sets unique classes on each component so that component styles will be applied correctly.
Fixes #46
=> Include components from addons

lib/component-css-postprocessor.js
The ComponentCssPostprocessor was hard-coded to write to
dist/assets/vendor.js, which meant that it was putting the required code
in that file even if the actual uglified vendor files was named
vendor-abc123.js or whatever.
Fixes #52
=> Find uglified vendor.js files to append to

lib/component-css-postprocessor.js
Currently after appending `cssInjectionSource` to already fingerprinted `vendor.js`, file is not re-fingerprinted, and this causes a bug when ember app is being delivered via CDNs and the latter has http cache configured (e. g. `aws s3` and `cloudfront`) - css namespace classes change, but browser gets an older version of a file (because fingerprint hasn't changed). This PR fixes this.
=> recalculate vendor.js hash

lib/broc-component-css-preprocessor.js
Fixes #75.
As far as I can see, caching the guids should have no implications like stale browser cache, etc.
=> enhancement: cache pod guids

lib/component-css-postprocessor.js
Nested components that use the `.` separator weren't being resolved correctly. With angle-bracket components, dot style will probably become much more common.
=> Fixes nested component class lookup for components that use '.' instead of '/'

lib/pod-style.js, lib/preprocess-class-names.js
This is separated into .styl .sass .scss and .less fixes #126 and #127
* Note *
After tests are updated, we can try to find a more unified verson of the the class name preprocessing
for more speed and better parity support
=> Switched back to the previous class name preprocessing

lib/component-names.js, package.json
so as not to conflict with other namespaces addresses #116
this will add a class like `_foo` to the components. 
@ebryn @topaxi @buschtoens care to weigh in? I know that you @ebryn had addressed concerns over predictable, and proposed that we use some type of deterministic hashing algorithm instead. Is that still desired?
=> moving to a 'private' class name

index.js
Hi @ebryn; Hi @webark -
We're seeing a small, but blocking issue with release "0.2.0-beta.3". The [first patch](https://github.com/ebryn/ember-component-css/commit/712637e4e352873987f677870de2c2d002645d63) is great and resolves some small styling quirks we were seeing. But, the [second patch](https://github.com/ebryn/ember-component-css/commit/441fa1fb169ebf236834124861f5f53f3b667755) prevents our Ember app from starting.
This is the specific error during `ember s`:
```
The Broccoli Plugin: [PodStyles] failed with:
TypeError: Cannot read property 'length' of undefined
```
It seems the second patch was to use `app.registry.extensionsForType('css')` instead of `this.registry.extensionsForType('css')`. What we're seeing is the previous output from `this.registry.extensionsForType('css')` was …
=> Filter undefined type extensions

index.js
needing to base the configs off of the passed in app.
Also, including all of the addon's app space in the main funnel. This is a start to fixing #143 
One caveat with this is that in order to use it in the addon, you have to put the styles inside the app directories rather then the addon, and ALL podstyles get bundled together. Meaning from both your apps and your addons all in the same pod-styles files.
=> Support for use inside of addons.

lib/pod-style.js, lib/preprocess-class-names.js, package.json
This is in lieu of just wrapping them in the namespace. Feel like it's a little cleaner, and less apt to have wacky edgecase errors that might come up by just wrapping the content. Stylus and Sass still are just indenting.
=> Moves processing of namespace selectors to postcss for sass and less

index.js, lib/include-all.js
Putting this out there for discussion. Major benefits are that we can get more detailed sourcemaps due to each file being imported separately into the manifest file. Also, we only have to modify this file when we add or delete a styles.scss file, not when any css is changed. 
Downsides are that it take a little longer due to the preprocessor having to take the extra weight of importing all the files. More so requires the eventual consumer of this file to be able to import css files in an expected and supported way.
@topaxi @ebryn `@anyonehere` please comment as to any feedback you might have.
=> Using a manifest file for the pod-styles rather then a concatenated file.

addon/initializers/component-styles.js
There have been instances where it would have been nice to be able to grab the component class that get's generated and potentially add it a different area/component (with ember-wormhole for instance). This will also allow you to choose not to have the class appended to a given component if you wish as well.
=> Using a computed property for the class name that get's added.

tests/acceptance/less-test.js, tests/acceptance/sass-test.js, tests/acceptance/scss-test.js, tests/acceptance/styl-test.js, tests/dummy/app/components/base-rules/component.js, tests/dummy/app/components/base-rules/template.hbs, tests/dummy/app/components/less/base-rules/styles.less, tests/dummy/app/components/sass/base-rules/styles.sass, tests/dummy/app/components/scss/base-rules/styles.scss, tests/dummy/app/components/styl/base-rules/styles.styl
Updated these to be a better use case. We now have access to the `componentCssClassName` variable. We can use this variable in the templates to facilitate basic BEM css definitions.
Would like to add in the ability to make this more seamless in the future, and add to docs.
=> updated the BEM tests

README.md
so that we child addons can work properly. Reference https://github.com/ember-cli/ember-cli/issues/3531#issuecomment-81133458 . This was brought up in issue #181
=> made a note to use the proper super include call

addon/pod-names.js
This addresses #184. By creating a empty pod-name file, the file is guaranteed to alway be there, even if we don't want it like in the case of turning off name-spacing.
=> Default empty pod name file

index.js
We are using ember-component-css in conjunction with ember-engines. Our engines are in-repo addons, and we have an additional in-repo addon for our app that contains shared components to be consumed by both the main app and the in-repo engines.
This pattern works fine except that currently ember-cli will throw an error in the `included` hook for the addon: `Cannot read property app of undefined`. I have a repro ember-cli repo here:
https://github.com/sohara/in-repo-component-css
This patch is simple guard agains accessing nested props on `app` that are not defined, but perhaps there's a better guard or other approach.
=> Support in-repo engines dependent on in-repo addons

addon/initializers/component-styles.js, package.json
The polyfill is now available through the Ember object, no need to import it anymore!
=> Update ember-getowner-polyfill to avoid deprecation warnings

index.js
Due to the odd nature of 'glob', you can't have a set of just one item. So adding an extra ',' at the end so that you will always have at least two "items" in the set
Closes #178, #204
=> Fixing an oddity in the glob syntax for including files.

ember-cli-build.js, package.json, tests/acceptance/scss-test.js, tests/dummy/app/components/scss/for-loop/component.js, tests/dummy/app/components/scss/for-loop/styles.scss, tests/dummy/app/components/scss/for-loop/template.hbs, tests/dummy/app/scss/template.hbs
=> Now allowing namespaceing of rules deinfed inside of a scss @ for rule

package.json, tests/dummy/lib/no-style-files-yet/package.json, tests/dummy/lib/second-test-addon/package.json, tests/dummy/lib/test-addon/package.json
able to use multiple differnt css preprocessors into one. closes #221
=> fix(npm dependencies): published what was being used for test css compiling

README.md
I seriously just wasted 4 hours debugging this, had to read the source code to see how these were supposed to be setup. 
This dir structure was not obvious to me as I am used to seeing the addon styles in the `addon/app` dir. 
Please accept this change to save people (and me when I will inevitably forget how it should be done) time.
=> Updates README instructions for use in addons

package.json
Any particular reason why this is pinned at this specific version?
=> Unpin broccoli-persistent-filter

package.json, yarn.lock
Now the order of files in the manifest is sorted first by depth, then by alphanumeric.
=> updated broccoli style manifest

README.md, addon/mixins/style-namespacing-extras.js, app/initializers/component-styles.js, app/initializers/route-styles.js, tests/dummy/app/components/base-rules/template.hbs, tests/dummy/app/components/scss/for-loop/template.hbs, tests/dummy/lib/no-style-files-yet/addon/components/no-style/template.hbs, tests/dummy/lib/second-test-addon/addon/components/second-addon-less/template.hbs, tests/dummy/lib/test-addon/addon/components/addon-scss/template.hbs
`componentCssClassName` will be officially deprecated, then removed in future versions. Will be migrating to the more appropriately named `styleNamespace`
=> now upgrading to using 'styleNamespace'

README.md
The README had an incomplete instruction that was not working for plain CSS. That part has been updated
=> Fix for usage in CSS

README.md, index.js
This PR aims to add a configuration option that excludes a pattern of style files from the style manifest.
**A use case example for this PR:**
I want to have a separate style file for each media-query breakpoint. With pods, this means having multiple styles files in a component or route directory.
```
.
└── my-component/
├── _style-1366.scss
├── _style-960.scss
├── main.scss
├── component.js
└── template.hbs
```
In order to control the order in which the `_style-*` files will be read, I import them manually from `main.scss`
```sass
// main.scss
@import "./_style-1366"
@import "./_style-960"
```
The problem is that now these two files are imported twice. I want to remove them from the styles import manifest that broccoli-style-manifest generates.
```
ENV['ember-component-css'] = { …
```
=> add config option to exclude style files from manifest

README.md
Found an edge case where my addon was run before ember-component-css, leading to styles not being applied in the host app since the component's did not have the expected class names associated.
So I documented in README :)
=> Add notes for addon developers

.npmignore, .travis.yml, CONTRIBUTING.md, config/ember-try.js, package.json, yarn.lock
Also updates Ember to 3.6.1 (3.6.0 had a couple nasty bugs), removes an unused ember-try scenario and other small changes 
Done with `ember-cli-update`.
=> Update to Ember-cli 3.6

addon/instance-initializers/route-styles.js
When aborting a transition on an initial load where the transition's `from` is `null` the router sets the `to` the `from` of the transition you where coming from. Putting a guard against this null `to` value now.
fixes #323
=> gaurding against transitions without a 'to'

.travis.yml, addon/instance-initializers/route-styles.js, package.json, tests/acceptance/aborted-state-test.js, tests/dummy/app/aborted-state/route.js, tests/dummy/app/aborted-state/template.hbs, tests/dummy/app/router.js, yarn.lock
This was happening when a transition is aborted when first loading the application and there isn't a from route yet, like ember-simple-auth is doing this if you are trying to access an authenticated route.
=> making sure that the route info object has the right shape before continuing

README.md
My `ember-component-css@0.6.9` styles weren't being applied to an addon, and I had no console output giving me any clues.
My co-worker figured out that, since my addon was using SASS for styling, I also needed to move `ember-cli-sass` to the `dependencies` key of my addon's `package.json`.
While this is an `ember-cli-sass` gotcha, and nothing that `ember-component-css` can fix, these docs might help other folks who hit the same issue.
=> docs: adds ember-cli-sass gotcha for addons

index.js
opt-in to address #365 until [ember-cli-styles](https://github.com/webark/ember-cli-styles) has stable release.
This would allow you to specify in `config/environment.js`:
```js
'ember-component-css': {
patchClassicComponent: false
}
```
Avoid the deprecation `Reopening the Ember.Component super class itself is deprecated` if you do not use classic components (or the bindings on classic components, at least).
Similar to https://github.com/salsify/ember-css-modules/pull/251 and https://github.com/simplabs/ember-test-selectors/pull/721.
=> Allow to opt out of classic component patching
