- README.md
> Tweak install command in readme

- bower.json
- lib/component-css-postprocessor.js
> override componentFor

- lib/component-css-preprocessor.js
- tests/dummy/app/acceptance/tests/app-styles-in-assets/component.js
- tests/dummy/app/acceptance/tests/app-styles-in-assets/expectation.js
- tests/dummy/app/styles/app.css
Looks like ComponentCssPreprocessor.toTree just wasn't processing the app/styles/app.css file.
> process app/styles/app.css - fix #68

- lib/component-css-postprocessor.js
> add check for class duplication

- bower.json
- lib/broc-component-css-preprocessor.js
- package.json
- tests/dummy/app/acceptance/tests/multiple-self-selector/component.js
- tests/dummy/app/acceptance/tests/multiple-self-selector/expectation.js
- tests/dummy/app/acceptance/tests/multiple-self-selector/styles.css
Switching CSS parser as discussed in #50 (isn't really related to #50 though).
> Use postcss instead of rework

- lib/broc-component-css-preprocessor.js
> Disable :root selectors from postcss-selector-namespace

- index.js
This is so that other addons can modify it. Fixes #34
> Switching to the apps registry rather then the addons

- lib/lookup-reopen/main.js
Patch for supporting 2+ level components hierarchy and applying className only once
> Patch for supporting 2+ level components hierarchy and applying className only once

- tests/acceptance/template-style-only-test.js
- tests/dummy/app/components/template-and-style/styles.scss
- tests/dummy/app/components/template-and-style/template.hbs
- tests/dummy/app/router.js
- tests/dummy/app/template-style-only/template.hbs
Sometimes you will want to have a component that only has a template file that you still wish to style. This should be possible.
> this is a test for using a pod style with only a tempate and a style file

- bin/install-test-addons.sh
- index.js
- package.json
- tests/acceptance/addon-less-test.js
- tests/acceptance/addon-scss-test.js
- tests/dummy/app/addon/less/template.hbs
- tests/dummy/app/addon/scss/template.hbs
- tests/dummy/app/router.js
- tests/dummy/lib/.jshintrc
- tests/dummy/lib/second-test-addon/addon/components/second-addon-less/component.js
- tests/dummy/lib/second-test-addon/addon/components/second-addon-less/styles.less
- tests/dummy/lib/second-test-addon/addon/components/second-addon-less/template.hbs
- tests/dummy/lib/second-test-addon/addon/styles/addon.less
- tests/dummy/lib/second-test-addon/app/components/second-addon-less/component.js
- tests/dummy/lib/second-test-addon/index.js
- tests/dummy/lib/second-test-addon/package.json
- tests/dummy/lib/test-addon/addon/components/addon-scss/component.js
- tests/dummy/lib/test-addon/addon/components/addon-scss/styles.scss
- tests/dummy/lib/test-addon/addon/components/addon-scss/template.hbs
- tests/dummy/lib/test-addon/addon/styles/addon.scss
- tests/dummy/lib/test-addon/app/components/addon-scss/component.js
- tests/dummy/lib/test-addon/index.js
- tests/dummy/lib/test-addon/package.json
using the tree for addon-styles, adding in the component styles from inside that addon directory, and then adding these to the style tree as a whole to grab all styles together fixes #143
> support for use inside of addons. 

- package.json
- tests/acceptance/css-test.js
- tests/dummy/app/components/css/base-rules/component.js
- tests/dummy/app/components/css/base-rules/styles.css
- tests/dummy/app/css/template.hbs
- tests/dummy/app/router.js
- tests/dummy/app/styles/app.css
This would be assuming that you would be using postcss with postcss-import.
> added in plain css tests.

- package.json
- tests/acceptance/sass-test.js
- tests/acceptance/scss-test.js
- tests/dummy/app/components/sass/base-rules/styles.sass
the only @ rules that are now respected are media and supports
Closes #191
> no longer namespacing children of @ rules

- config/ember-try.js
due to the good possiblity that there are users that are still on sub 2.x versions
> Adding in a 1.13 ember try scenario

- README.md
The issue that had orision was fixed with PR #208
> Update plain css instructions

- index.js
- lib/component-names.js
- lib/pod-names.js
- lib/pod-style.js
An effort to reduce class names to a minimal length in order to facilitate smaller file css file sizes.
> feat(optimization): ability to use terse class names to reduce css size

- index.js
Using the '_findHost' with a shim to get the root app, then grabbing the environment from that.
Closes #231
@rwwagner90 This is what we where talking about earlier.
> getting the 'root app', to get the proper environment

- lib/pod-names.js
I've used the same approach as @deepan83 but I think this one can be a little more performant.
> Merge pod names files

- app/initializers/route-styles.js
in the routers didTransition. fixes #266
> fix(router): accidentally removed a import super call 

- addon/mixins/style-namespacing-extras.js
> Mixins created with an empty create breaks ember-inspector

- README.md
Minor if statement syntax issue for the `customBinding` example
> Fixing example in readme

- addon/initializers/route-styles.js
- addon/instance-initializers/route-styles.js
- addon/utils/init-route-styles.js
- app/initializers/route-styles.js
- app/instance-initializers/route-styles.js
- index.js
- package.json
> Fix 3.6 deprecations

- .travis.yml
- index.js
Trying out setting the `_allPodStyles` variable on the host app to prevent multiple copies of this instance variable existing.
🤞
> Fix of addon and multiple copy, local linking, or version discrepancies

- addon/instance-initializers/route-styles.js
This is a stop gap for these cases to unblock and fix #320 
Will loop back around with this and find a broken test without this fix to define when it happens, and to make sure it get's handled appropriately.
Would also be nice to find a way to better handle these intermediary transitions better.
> there's a chance that at times a transition will not have a 'to'

- CHANGELOG.md
Looks like it has never actually been released
> Remove 0.6.6 from changelog
